on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-prod

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          draft-pull-request: true
          labels: "prod: pending"
          release-labels: "prod: tagged"
          pull-request-title-pattern: "chore(prod): release${component} ${version}"
