on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please-test:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          default-branch: master
          changelog-path: CHANGELOG-Test.md
          prerelease: true
          versioning-strategy: prerelease
          component: test
          monorepo-tags: true

  release-please:
    needs: release-please-test
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          default-branch: master
          component: prod
          monorepo-tags: true
          draft-pull-request: true
          changelog-path: CHANGELOG-Prod.md
          release-as: 1.2.0
