on:
  push:
    branches:
      - prod

permissions:
  contents: write
  pull-requests: write

name: release-please-prod

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          default-branch: prod
