on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-uat

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          changelog-path: CHANGELOG-Test.md
          prerelease: true
          versioning-strategy: prerelease
          component: test
          monorepo-tags: true
          draft-pull-request: true
