on:
  push:
    branches:
      - aaa

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        name: release-please-test
        with:
          release-type: go
          default-branch: aaa
          changelog-path: CHANGELOG-Test.md
          prerelease: true
          versioning-strategy: prerelease
          component: test
          monorepo-tags: true

      - uses: google-github-actions/release-please-action@v3
        name: release-please-prod
        with:
          release-type: go
          default-branch: aaa
          component: prod
          monorepo-tags: true
          draft-pull-request: true
          changelog-path: CHANGELOG-Prod.md
