on:
  push:
    branches:
      - uat

permissions:
  contents: write
  pull-requests: write

name: release-please-uat

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          prerelease: true
          default-branch: uat
          versioning-strategy: prerelease
          monorepo-tags: true
          component: test
